[project]
name = 'Indigenous-Land-Rights-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.benefits-sharing]
path = 'contracts/benefits-sharing.clar'
clarity_version = 2
epoch = 2.5

[contracts.community-verification]
path = 'contracts/community-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.territory-mapping]
path = 'contracts/territory-mapping.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-rights]
path = 'contracts/usage-rights.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
